# Practice 1

## Instructions

You're going to practice working in pandas. 


You'll walk through instantiating a `DataFrame`, reading data into it, looking at and examining that data, and then playing with it. 


A dataset on the [quality of red wines](https://archive.ics.uci.edu/ml/datasets/wine+quality) is used for this purpose.
It is located in the `data` folder within this directory. It's called `winequality-red.csv`. 


Typically, we use Jupyter notebooks like this for a very specific set of things - presentations and EDA. 


Today, as we'll be playing around with `pandas`, much of what we'll be doing is considered EDA. Therefore, by using a notebook, we'll get a tighter feedback loop with our work than we would trying to write a script. But, in general, **we do not use Jupyter notebooks for development**. 

Below, we've put a set of questions and then a cell for you to work on answers. However, feel free to add additional cells if you'd like. Often it will make sense to use more than one cell for your answers.

## Assignment Questions

### Part 1 - The Basics of DataFrames

Let's start off by following the general workflow that we use when moving data into a DataFrame: 

    * Importing pandas
    * Reading data into the DataFrame
    * Getting a general sense of the data

So, in terms of what you should do for this part...

1. Import pandas

In [2]:
import pandas as pd

2. Read the wine data into a DataFrame.

In [6]:
df = pd.read_csv("./data/winequality-red.csv", sep=";")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [15]:
df.sample(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
306,7.6,0.620,0.32,2.2,0.082,7.0,54.0,0.99660,3.36,0.52,9.4,5
100,8.3,0.610,0.30,2.1,0.084,11.0,50.0,0.99720,3.40,0.61,10.2,6
1130,9.1,0.600,0.00,1.9,0.058,5.0,10.0,0.99770,3.18,0.63,10.4,6
613,8.2,0.390,0.38,1.5,0.058,10.0,29.0,0.99620,3.26,0.74,9.8,5
763,9.3,0.655,0.26,2.0,0.096,5.0,35.0,0.99738,3.25,0.42,9.6,5
47,8.7,0.290,0.52,1.6,0.113,12.0,37.0,0.99690,3.25,0.58,9.5,5
44,6.8,0.670,0.02,1.8,0.050,5.0,11.0,0.99620,3.48,0.52,9.5,5
894,7.2,0.630,0.03,2.2,0.080,17.0,88.0,0.99745,3.53,0.58,9.8,6
426,6.4,0.670,0.08,2.1,0.045,19.0,48.0,0.99490,3.49,0.49,11.4,6
478,9.6,0.680,0.24,2.2,0.087,5.0,28.0,0.99880,3.14,0.60,10.2,5

3. Use the `attributes` and `methods` available on DataFrames to answer the following questions: 
    * How many rows and columns are in the DataFrame?
    * What data type is in each column?
    * Are all of the variables continuous, or are any categorical?
    * How many non-null values are in each column?
    * What are the min, mean, max, median for all numeric columns?

In [22]:
n_rows, n_cols = df.shape
df.info()

print(f"""
ANSWERS
=======
- the DataFrame contains {n_rows} rows and {n_cols} columns
- all are float except `quality`
- `quality` is categorical
- all data is non-null
""")

df.describe(percentiles=[0.5]).transpose()

<class 'pandas.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

ANSWERS
=======
- the DataFrame contains 1599 rows and 12 columns
- all are float except `quality`
- `quality` is categorical
- all data is non-null

,count,mean,std,min,50%,max
fixed acidity,1599.0,8.319637,1.741096,4.60000,7.90000,15.90000
volatile acidity,1599.0,0.527821,0.179060,0.12000,0.52000,1.58000
citric acid,1599.0,0.270976,0.194801,0.00000,0.26000,1.00000
residual sugar,1599.0,2.538806,1.409928,0.90000,2.20000,15.50000
chlorides,1599.0,0.087467,0.047065,0.01200,0.07900,0.61100
free sulfur dioxide,1599.0,15.874922,10.460157,1.00000,14.00000,72.00000
total sulfur dioxide,1599.0,46.467792,32.895324,6.00000,38.00000,289.00000
density,1599.0,0.996747,0.001887,0.99007,0.99675,1.00369
pH,1599.0,3.311113,0.154386,2.74000,3.31000,4.01000
sulphates,1599.0,0.658149,0.169507,0.33000,0.62000,2.00000
alcohol,1599.0,10.422983,1.065668,8.40000,10.20000,14.90000
quality,1599.0,5.636023,0.807569,3.00000,6.00000,8.00000

### Part 2 - Practice with Grabbing Data

Let's now get some practice with grabbing certain parts of the data. If you'd like some extra practice, try answering each of the questions in more than one way (because remember, we can often grab our data in a couple of different ways).

1. Grab the first 10 rows of the `chlorides` column.

In [ ]:
df.chlorides.head(10)

0    0.076
1    0.098
2    0.092
3    0.075
4    0.076
Name: chlorides, dtype: float64

2. Grab the last 10 rows of the `chlorides` column.

In [25]:
df.chlorides.tail(10)

1589    0.073
1590    0.077
1591    0.089
1592    0.076
1593    0.068
1594    0.090
1595    0.062
1596    0.076
1597    0.075
1598    0.067
Name: chlorides, dtype: float64

3. Grab indices 264-282 of the `chlorides` **and** `density` columns.

In [28]:
df[["chlorides", "density"]].loc[264:282]

     chlorides  density
264      0.064  0.99990
265      0.071  0.99680
266      0.096  1.00025
267      0.078  0.99730
268      0.077  0.99870
269      0.104  0.99960
270      0.087  0.99650
271      0.104  0.99960
272      0.071  0.99935
273      0.076  0.99735
274      0.088  0.99915
275      0.087  0.99650
276      0.077  0.99870
277      0.104  0.99960
278      0.073  0.99760
279      0.087  0.99910
280      0.071  0.99860
281      0.358  0.99720
282      0.067  0.99710

4. Grab all rows where the `chlorides` value is less than 0.10.

In [31]:
df.query("chlorides < 0.10")

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

5. Now grab all the rows where the `chlorides` value is greater than the column's mean (try **not** to use a hard-coded value for the mean, but instead a method).

In [39]:
avg_chlorides = df.chlorides.mean()
query = "chlorides > @df.chlorides.mean()"

print(f"{avg_chlorides=}")
print(query)

df.query(query)

avg_chlorides=np.float64(0.08746654158849279)
chlorides > @df.chlorides.mean()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
10,6.7,0.580,0.08,1.8,0.097,15.0,65.0,0.99590,3.28,0.54,9.2,5
12,5.6,0.615,0.00,1.6,0.089,16.0,59.0,0.99430,3.58,0.52,9.9,5
13,7.8,0.610,0.29,1.6,0.114,9.0,29.0,0.99740,3.26,1.56,9.1,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1558,6.9,0.630,0.33,6.7,0.235,66.0,115.0,0.99787,3.22,0.56,9.5,5
1570,6.4,0.360,0.53,2.2,0.230,19.0,35.0,0.99340,3.37,0.93,12.4,6
1578,6.8,0.670,0.15,1.8,0.118,13.0,20.0,0.99540,3.42,0.67,11.3,6
1591,5.4,0.740,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6,6
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5

6. Grab all those rows where the `pH` is greater than 3.0 and less than 3.5.

In [46]:
df.query("3.0 < pH < 3.5")

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0,7
...,...,...,...,...,...,...,...,...,...,...,...,...
1592,6.3,0.51,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1593,6.8,0.62,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
1594,6.2,0.60,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1596,6.3,0.51,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1598,6.0,0.31,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6


7. Further filter the results from 6 to grab only those rows that have a `residual sugar` less than 2.0.

In [50]:
df.query(
"3.0 < `pH` < 3.5 "
"and `residual sugar` < 2.0"
)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0,7
10,6.7,0.58,0.08,1.8,0.097,15.0,65.0,0.99590,3.28,0.54,9.2,5
13,7.8,0.61,0.29,1.6,0.114,9.0,29.0,0.99740,3.26,1.56,9.1,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1569,6.2,0.51,0.14,1.9,0.056,15.0,34.0,0.99396,3.48,0.57,11.5,6
1576,8.0,0.30,0.63,1.6,0.081,16.0,29.0,0.99588,3.30,0.78,10.8,6
1578,6.8,0.67,0.15,1.8,0.118,13.0,20.0,0.99540,3.42,0.67,11.3,6
1590,6.3,0.55,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,6
1593,6.8,0.62,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6

### Part 3 - More Practice

Let's move on to some more complicated things. Use your knowledge of `groupby`s, `sorting` to answer the following.

1. Get the average amount of `chlorides` for each `quality` value.

In [54]:
print("Average `chlorides` groped by `quality`")
(df
 .groupby("quality")
 .chlorides.mean()
)

Average `chlorides` groped by `quality`

quality
3    0.122500
4    0.090679
5    0.092736
6    0.084956
7    0.076588
8    0.068444
Name: chlorides, dtype: float64

 2. For observations with a `pH` greater than 3.0 and less than 4.0, find the average `alcohol` value by `pH`.

In [55]:
(df
 .query("3.0<`pH`<4.0")
 .groupby("pH")
 .alcohol.mean()
)

pH
3.01    11.320000
3.02    10.200000
3.03     9.633333
3.04     9.740000
3.05    10.050000
          ...
3.74    11.500000
3.75    10.500000
3.78    12.400000
3.85    12.900000
3.90    12.950000
Name: alcohol, Length: 75, dtype: float64

In [ ]:
import numpy as np

df_acid = df.query("3.0<`pH`<4.0")
groups = pd.cut(df_acid.pH, np.arange(3.0, 4.0, 0.1))
(df_acid
 .groupby(groups)
 .alcohol
 .mean()
 )

pH
(3.0, 3.1]    10.065320
(3.1, 3.2]    10.213255
(3.2, 3.3]    10.395696
(3.3, 3.4]    10.411461
(3.4, 3.5]    10.476027
(3.5, 3.6]    10.797083
(3.6, 3.7]    11.093750
(3.7, 3.8]    12.309091
(3.8, 3.9]    12.933333
Name: alcohol, dtype: float64

3. For observations with an `alcohol` value between 9.25 and 9.5, find the highest amount of `residual sugar`.

In [59]:
df.query("9.25 < alcohol < 9.5")["residual sugar"].max()

np.float64(10.7)

4. Create a new column, called `total_acidity`, that is the sum of `fixed acidity` and `volatile acidity`.

In [ ]:
df.eval("total_acidity = `fixed acidity` + `volatile acidity`")

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,total_acidity
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,8.100
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,8.680
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,8.560
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,11.480
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,8.100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,6.800
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,6.450
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,6.810
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,6.545
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,6.310

5. Find the average `total_acidity` for each of the `quality` values.

In [63]:
(df
 .eval("total_acidity = `fixed acidity` + `volatile acidity`")
 .groupby("quality")
 ["total_acidity"].mean()
 )

quality
3    9.244500
4    8.473208
5    8.744295
6    8.844663
7    9.276281
8    8.990000
Name: total_acidity, dtype: float64

6. Find the top 5 `density` values.

In [71]:
df.density.sort_values(ascending=False).head(5)

1434    1.00369
1435    1.00369
442     1.00320
554     1.00315
555     1.00315
Name: density, dtype: float64

7. Find the 10 lowest `sulphates` values.

In [72]:
df.sulphates.sort_values().head(10)

170     0.33
1369    0.37
1287    0.37
1347    0.39
1348    0.39
65      0.39
837     0.39
64      0.39
836     0.39
1237    0.40
Name: sulphates, dtype: float64